import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import Dragon from '../../components/shared/Dragon';

export default function Born() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Born!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <main className={styles.main}>
        <h2 className="text-base font-bold text-4xl pb-6">
          🎉 Congrats, your dragon was born! 🎉
        </h2>
        <Dragon level={1} />
        <p className={styles.description}>
          <Link href="/hatchery/welcome/">Continue</Link>
        </p>
      </main>
    </div>
  );
}
