import { useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import Hatching from '../../components/hatchery/hatching';
// import Dragon from '../../components/shared/Dragon';
import { useRouter } from 'next/router';

export default function Hatchery() {
  const [step, setStep] = useState(0);
  const router = useRouter();

  useEffect(() => {
    if (step == 3) {
      setTimeout(() => {
        router.push('/hatchery/born/');
      }, 1500);
    }
  }, [step, router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Hatchery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to SEEK The Dragon</h1>

        <p className={styles.description}>Click on the egg </p>

        <div className={styles.grid}>
          <Hatching step={step} setStep={setStep} />
        </div>
      </main>
    </div>
  );
}
