import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import Image from 'next/image';
import welcome from '../../components/hatchery/welcome';
import Dragon from '../../components/shared/Dragon';

export default function Hatchery() {

  const [name, setName] = useState("Dragon");

  return (
    <div className={styles.container}>
      <Head>
        <title>Setup your name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>

        <p className={styles.description}>
          Input your name
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Dragon width='100px' height='100px' />
          </div>
          <div className={styles.card}>
            <input value={name} onChange={(e) => setName(e.target.value)} />
            <Link href="/next-step/">Save</Link>
          </div>
        </div>
      </main>

    </div>
  )
}
