import { useState, useContext } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import styles from '../../styles/Home.module.css';
import Image from 'next/image';
import welcome from '../../components/hatchery/welcome';
import Dragon from '../../components/shared/Dragon';
import { ContextApp } from '../../reducers';

export default function Hatchery() {
  const [name, setName] = useState('Dragon');
  const { state, dispatch } = useContext(ContextApp);
  const router = useRouter();

  const onSave = () => {
    dispatch({
      type: 'updateName',
      payload: {
        profile: { ...state.profile, name },
      },
    });
    router.push('/map/');
  };

  console.log('----state', state);

  return (
    <div className={styles.container}>
      <Head>
        <title>Setup your name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>

        <p className={styles.description}>Input your name</p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Dragon width="100px" height="100px" />
          </div>
          <div className={styles.card}>
            <input value={name} onChange={(e) => setName(e.target.value)} />
            <button onClick={onSave}>Save</button>
          </div>
        </div>
      </main>
    </div>
  );
}
