import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import welcome from '../components/hatchery/welcome';

export default function Hatchery() {

  const [name, setName] = useState("Dragon");


  console.log("welc name", name);

  return (
    <div className={styles.container}>
      <Head>
        <title>Setup your name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>

        <p className={styles.description}>
          Input your name
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            {/* Dragon pic */}
            {/* <Image src={""} alt="Click on me" width={256} height={338} />; */}
          </div>
          <div className={styles.card}>
            <input value={name} onChange={(e) => setName(e.target.value)} />
            <a href="/next-step/">Save</a>
          </div>
        </div>
      </main>

    </div>
  )
}
