import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl">
          Welcome to SEEK
        </h1>

        <p className={styles.description}>
          Get started
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2><Link href="/hatchery/">Join up &rarr;</Link></h2>
            <p>Create new Profile on SEEK</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{' '}
          <span className={styles.logo}>
          </span>
      </footer>
    </div>
  )
}
