import React, { useContext, useState } from "react";
import { ContextApp } from "../reducers";

import styles from "../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import wisedragon from "/public/wisedragon.gif";
import Image from "next/image";
import Dragon from "/Components/shared/Dragon";
import Typewriter from "typewriter-effect";

export default function Powerup() {
  const { state, dispatch } = useContext(ContextApp);
  let name = state.profile.name;
  let level = state.profile.level;

  // const [level, setLevel] = useState(0);
  const [text, setText] = useState(`Welcome, how may I help you?`);

  const levelUp = (e) => {
    e.preventDefault();
    dispatch({
      type: "updateLevel",
      payload: {
        profile: { ...state.profile, level: level + 1 },
      },
    });
  };

  // let level = 1;
  let secretName = "The Future Great Architech";
  let replyText1 = `This experience will grow you.`;
  let replyText2 = `This is what you’re going through, not who you are.`;
  let replyText3 = `This is tough, but you are tougher.`;
  return (
    <div>
      <Head>
        <title>Recharge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      {/* <main className={styles.main}> */}
      <main className="container mx-auto">
        <div className="menu">
          <div>
            <Link href="/map">Menu</Link>
          </div>
        </div>
        {/* <div className="container mx-auto"> */}
        {/* <div className="container mx-auto"> */}
        <div className="flex">
          <div style={{ maxWidth: 400 }} className="flex-1 ...">
            <p>Hey, {name}</p>
            <p>Level: {level}</p>
            <p>aka {secretName}</p>
            <div className="circle" onClick={(e) => levelUp(e)}>
              <div>Boost CV</div>
            </div>
            <div className="circle" onClick={(e) => levelUp(e)}>
              <div>Boost Education</div>
            </div>
            <div className="circle" onClick={(e) => levelUp(e)}>
              <div>Boost Industry knowledge</div>
            </div>
          </div>
          <div className="flex-1 ...">
            <Dragon width={500} height={500} />
          </div>
        </div>
      </main>
    </div>
  );
}
