import React, { useEffect } from "react";
import styles from "../styles/Home.module.css";
import profileStyles from "../styles/Profile.module.css";
import Head from "next/head";
import Link from "next/link";

function Profile() {
  let name = "Dragon name";
  let level = 5;
  let secretName = "The Future Great Architech";

  return (
    <div className={styles.container}>
      <Head>
        <title>Hatchery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>Welcome to SEEK The Dragon</h1> */}

        <div className={profileStyles.row}>
          <div className={profileStyles.column}>1 more contents</div>
          <div className={profileStyles.column}>2</div>
          <div className={profileStyles.column}>3</div>
        </div>

        <p>Hey, {name}</p>
        <p>{level}</p>
        <p>{secretName}</p>
        <p>Placeholder for dragon</p>
      </main>
    </div>
  );
}

export default Profile;
