import React, { useEffect, useContext } from 'react';
import { ContextApp } from '../reducers';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

function Profile() {
  const { state } = useContext(ContextApp);
  console.log('state', state);
  let name = state.profile.name;
  let level = state.profile.level;
  let secretName = 'The Future Great Architech';

  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <main className={styles.main}>
        {/* <div className="container mx-auto"> */}

        {/* <h1 className={styles.title}>Welcome to SEEK The Dragon</h1> */}

        <p>Hey, {name}</p>
        <p>{level}</p>
        <p>{secretName}</p>
        <p>Placeholder for dragon</p>
      </main>
    </div>
  );
}

export default Profile;
